global_parameters:
  annual_compensation_increase_rate: 0.028
  attrition:
    annual_termination_rate: 0.15
    new_hire_termination_rate: 0.25
    use_expected_attrition: false
  census_template_path: data/census_template.parquet
  cola_hazard:
    by_year:
      2025: 0.016
      2026: 0.014
      2027: 0.01
      2028: 0.008
      2029: 0.006
  compensation:
    COLA_rate: 0.02
    merit_dist:
      1:
        mu: 0.035
        sigma: 0.01
      2:
        mu: 0.04
        sigma: 0.012
      3:
        mu: 0.045
        sigma: 0.015
      4:
        mu: 0.05
        sigma: 0.02
    new_hire:
      age_mean: 44.5
      age_std: 11.6
    promo_raise_pct:
      0_to_1: 0.1
      1_to_2: 0.1
      2_to_3: 0.1
      3_to_4: 0.1
  days_into_year_for_cola: 182
  days_into_year_for_promotion: 182
  deterministic_termination: true
  dev_mode: true
  log_level: DEBUG
  maintain_headcount: false
  max_working_age: 63
  min_working_age: 22
  monthly_transition: false
  new_hire_age_std_dev: 4
  new_hire_average_age: 25
  new_hires:
    new_hire_rate: 0.48
  onboarding:
    early_tenure_months: 6
    enabled: true
    hazard_multiplier: 1.5
    productivity_curve:
    - 0.8
    - 0.85
    - 0.9
    - 0.95
    - 1.0
    - 1.0
  projection_years: 3
  promotion_hazard:
    age_multipliers:
      30-39: 1.1
      40-49: 0.9
      50-59: 0.4
      60-65: 0.1
      <30: 1.5
    base_rate: 0.105
    level_dampener_factor: 0.14
    tenure_multipliers:
      1-3: 1.7
      10-15: 0.3
      15+: 0.08
      3-5: 2.0
      5-10: 1.1
      <1: 0.4
  promotion_matrix_path: null
  raises_hazard:
    merit_base: 0.026
    merit_low_level_bump_value: 0.003
    merit_low_level_cutoff: 2
    merit_tenure_bump_bands:
    - <1
    - 1-3
    - 3-5
    merit_tenure_bump_value: 0.002
    promotion_raise: 0.1
  random_seed: 79
  start_year: 2025
  target_growth: 0.032
  termination_hazard:
    age_multipliers:
      30-39: 0.9
      40-49: 1.1
      50-59: 1.2
      60-65: 10.0
      65+: 10.0
      <30: 0.25
    base_rate_for_new_hire: 0.042
    level_discount_factor: 0.08
    min_level_discount_multiplier: 0.5
    tenure_multipliers:
      1-3: 0.7
      10-15: 0.13
      15+: 0.26
      3-5: 0.45
      5-10: 0.22
      <1: 0.2
job_levels:
- avg_annual_merit_increase: 0.03
  comp_age_factor: 0.005
  comp_base_salary: 40000
  comp_stochastic_std_dev: 0.1
  description: Non-exempt employees paid hourly wages
  job_families:
  - Operations
  - Facilities
  level_id: 0
  max_compensation: 55000
  min_compensation: 0
  name: Hourly
  promotion_probability: 0.08
  target_bonus_percent: 0.0
- avg_annual_merit_increase: 0.035
  comp_age_factor: 0.006
  comp_base_salary: 65000
  comp_stochastic_std_dev: 0.1
  description: Entry-level exempt employees, individual contributors
  job_families:
  - Engineering
  - HR
  - Finance
  - IT
  level_id: 1
  max_compensation: 80000
  min_compensation: 56000
  name: Staff
  promotion_probability: 0.12
  target_bonus_percent: 0.05
- avg_annual_merit_increase: 0.04
  comp_age_factor: 0.007
  comp_base_salary: 95000
  comp_stochastic_std_dev: 0.1
  description: First-level management with direct reports
  job_families:
  - Engineering
  - HR
  - Finance
  - IT
  level_id: 2
  max_compensation: 120000
  min_compensation: 81000
  name: Manager
  promotion_probability: 0.08
  target_bonus_percent: 0.15
- avg_annual_merit_increase: 0.045
  comp_age_factor: 0.008
  comp_base_salary: 140000
  comp_stochastic_std_dev: 0.1
  description: Mid-level management, often managing other managers
  job_families:
  - Engineering
  - HR
  - Finance
  - IT
  level_id: 3
  max_compensation: 160000
  min_compensation: 121000
  name: SrMgr
  promotion_probability: 0.05
  target_bonus_percent: 0.2
- avg_annual_merit_increase: 0.05
  comp_age_factor: 0.01
  comp_base_salary: 250000
  comp_stochastic_std_dev: 0.15
  description: Senior leadership roles
  job_families:
  - Executive
  level_id: 4
  max_compensation: 10000000
  min_compensation: 161000
  name: Director
  promotion_probability: 0.02
  target_bonus_percent: 0.3
plan_rules:
  auto_enrollment:
    default_rate: 0.0
    enabled: false
    increase_high_rate: 0.0
    increase_to_match_rate: 0.0
    opt_down_target_rate: 0.0
    outcome_distribution:
      prob_increase_high: 0.0
      prob_increase_to_match: 0.0
      prob_opt_down: 0.0
      prob_opt_out: 0.0
      prob_stay_default: 1.0
    proactive_enrollment_probability: 0.0
    proactive_rate_range:
    - 0.0
    - 0.0
    re_enroll_existing: false
    window_days: 90
  auto_increase:
    cap_rate: 0.0
    enabled: false
    increase_rate: 0.0
  behavioral_params:
    prob_decrease_given_change: 0.3
    prob_increase_given_change: 0.4
    prob_stop_given_change: 0.05
    voluntary_change_probability: 0.1
    voluntary_decrease_amount: 0.01
    voluntary_default_deferral: 0.05
    voluntary_enrollment_rate: 0.2
    voluntary_increase_amount: 0.01
    voluntary_window_days: 180
  contributions:
    enabled: true
  eligibility:
    min_age: 21
    min_service_months: 0
  eligibility_events:
    event_type_map: {}
    milestone_months: []
    milestone_years: []
  employer_match:
    dollar_cap: 0.0
    tiers:
    - cap_deferral_pct: 0.0
      match_rate: 0.0
  employer_nec:
    rate: 0.01
  irs_limits:
    2024:
      catchup_eligibility_age: 50
      catchup_limit: 7500
      compensation_limit: 345000
      deferral_limit: 23000
    2025:
      catchup_eligibility_age: 50
      catchup_limit: 7500
      compensation_limit: 350000
      deferral_limit: 23500
    2026:
      catchup_eligibility_age: 50
      catchup_limit: 7500
      compensation_limit: 355000
      deferral_limit: 24000
    2027:
      catchup_eligibility_age: 50
      catchup_limit: 7500
      compensation_limit: 360000
      deferral_limit: 24500
    2028:
      catchup_eligibility_age: 50
      catchup_limit: 7500
      compensation_limit: 365000
      deferral_limit: 25000
    2029:
      catchup_eligibility_age: 50
      catchup_limit: 7500
      compensation_limit: 370000
      deferral_limit: 25500
  onboarding_bump:
    enabled: true
    method: sample_plus_rate
    rate: 0.05
scenarios:
  baseline:
    description: Default simulation parameters generated from historical data
    name: Baseline
