global_parameters: !!python/object/apply:types.SimpleNamespace
  state:
    annual_termination_rate: 0.15
    census_template_path: data/census_template.parquet
    compensation: !!python/object/apply:types.SimpleNamespace
      state:
        new_hire: !!python/object/apply:types.SimpleNamespace
          state:
            age_mean: 44.5
            age_std: 11.6
    days_into_year_for_cola: 182
    days_into_year_for_promotion: 182
    deterministic_termination: true
    job_levels:
    - !!python/object/apply:types.SimpleNamespace
      state:
        avg_annual_merit_increase: 0.03
        comp_age_factor: 0.003
        comp_base_salary: 35000
        comp_stochastic_std_dev: 0.58
        description: Non-exempt employees paid hourly wages
        job_families:
        - Operations
        - Facilities
        level_id: 0
        max_compensation: 55000
        min_compensation: 35000
        name: Hourly
        promotion_probability: 0.08
        target_bonus_percent: 0.0
    - !!python/object/apply:types.SimpleNamespace
      state:
        avg_annual_merit_increase: 0.035
        comp_age_factor: 0.012
        comp_base_salary: 61473.45
        comp_stochastic_std_dev: 0.213
        description: Entry-level exempt employees, individual contributors
        job_families:
        - Engineering
        - HR
        - Finance
        - IT
        level_id: 1
        max_compensation: 80000
        min_compensation: 50000
        name: Staff
        promotion_probability: 0.12
        target_bonus_percent: 0.05
    - !!python/object/apply:types.SimpleNamespace
      state:
        avg_annual_merit_increase: 0.04
        comp_age_factor: 0.012
        comp_base_salary: 180794.77
        comp_stochastic_std_dev: 0.242
        description: First-level management with direct reports
        job_families:
        - Engineering
        - HR
        - Finance
        - IT
        level_id: 2
        max_compensation: 120000
        min_compensation: 75000
        name: Manager
        promotion_probability: 0.08
        target_bonus_percent: 0.15
    - !!python/object/apply:types.SimpleNamespace
      state:
        avg_annual_merit_increase: 0.045
        comp_age_factor: 0.003
        comp_base_salary: 263614.81
        comp_stochastic_std_dev: 0.306
        description: Mid-level management, often managing other managers
        job_families:
        - Engineering
        - HR
        - Finance
        - IT
        level_id: 3
        max_compensation: 160000
        min_compensation: 110000
        name: SrMgr
        promotion_probability: 0.05
        target_bonus_percent: 0.25
    - !!python/object/apply:types.SimpleNamespace
      state:
        avg_annual_merit_increase: 0.05
        comp_age_factor: 0.003
        comp_base_salary: 315679.72
        comp_stochastic_std_dev: 0.306
        description: Senior leadership roles (VP, C-suite, etc.)
        job_families:
        - Executive
        level_id: 4
        max_compensation: 350000
        min_compensation: 150000
        name: Exec
        promotion_probability: 0.02
        target_bonus_percent: 0.4
    log_level: DEBUG
    maintain_headcount: false
    max_working_age: 65
    min_working_age: 22
    monthly_transition: false
    new_hire_age_std_dev: 5
    new_hire_average_age: 30
    new_hire_rate: 0.17
    new_hire_termination_rate: 0.25
    onboarding: !!python/object/apply:types.SimpleNamespace
      state:
        early_tenure_months: 6
        enabled: true
        hazard_multiplier: 1.5
        productivity_curve:
        - 0.8
        - 0.85
        - 0.9
        - 0.95
        - 1.0
        - 1.0
    projection_years: 5
    random_seed: 42
    role_distribution: !!python/object/apply:types.SimpleNamespace
      state:
        Executive: 0.15
        Manager: 0.35
        Staff: 0.5
    start_year: 2025
    target_growth: 0.03
    use_expected_attrition: false
plan_rules: !!python/object/apply:types.SimpleNamespace
  state:
    auto_enrollment: !!python/object/apply:types.SimpleNamespace
      state:
        default_rate: 0.0
        enabled: false
        increase_high_rate: 0.0
        increase_to_match_rate: 0.0
        opt_down_target_rate: 0.0
        outcome_distribution: !!python/object/apply:types.SimpleNamespace
          state:
            prob_increase_high: 0.0
            prob_increase_to_match: 0.0
            prob_opt_down: 0.0
            prob_opt_out: 0.0
            prob_stay_default: 1.0
        proactive_enrollment_probability: 0.0
        proactive_rate_range:
        - 0.0
        - 0.0
        re_enroll_existing: false
        window_days: 90
    auto_increase: !!python/object/apply:types.SimpleNamespace
      state:
        cap_rate: 0.0
        enabled: false
        increase_rate: 0.0
    behavioral_params: !!python/object/apply:types.SimpleNamespace
      state:
        prob_decrease_given_change: 0.3
        prob_increase_given_change: 0.4
        prob_stop_given_change: 0.05
        voluntary_change_probability: 0.1
        voluntary_decrease_amount: 0.01
        voluntary_default_deferral: 0.05
        voluntary_enrollment_rate: 0.2
        voluntary_increase_amount: 0.01
        voluntary_window_days: 180
    contributions: !!python/object/apply:types.SimpleNamespace
      state:
        enabled: true
    eligibility: !!python/object/apply:types.SimpleNamespace
      state:
        min_age: 21
        min_service_months: 0
    eligibility_events: !!python/object/apply:types.SimpleNamespace
      state:
        event_type_map: !!python/object/apply:types.SimpleNamespace []
        milestone_months: []
        milestone_years: []
    employer_match: !!python/object/apply:types.SimpleNamespace
      state:
        dollar_cap: 0.0
        tiers:
        - !!python/object/apply:types.SimpleNamespace
          state:
            cap_deferral_pct: 0.0
            match_rate: 0.0
    employer_nec: !!python/object/apply:types.SimpleNamespace
      state:
        rate: 0.01
    irs_limits: !!python/object/apply:types.SimpleNamespace
      state:
        '2024': !!python/object/apply:types.SimpleNamespace
          state:
            catchup_eligibility_age: 50
            catchup_limit: 7500
            compensation_limit: 345000
            deferral_limit: 23000
    onboarding_bump: !!python/object/apply:types.SimpleNamespace
      state:
        enabled: true
        method: sample_plus_rate
        rate: 0.05
scenarios: !!python/object/apply:types.SimpleNamespace
  state:
    baseline: !!python/object/apply:types.SimpleNamespace
      state:
        description: Default simulation parameters generated from historical data
        name: Baseline
