# in config/compensation.yaml
COLA_rate: 0.032

# if you want annual merit on top of COLA
merit_dist:
  0: {mu: 0.025, sigma: 0.01}
  1: {mu: 0.030, sigma: 0.012}
  2: {mu: 0.035, sigma: 0.015}
  3: {mu: 0.040, sigma: 0.015}
  4: {mu: 0.045, sigma: 0.020}

# (optionally) promotion bumps
promo_raise_pct:
  "0_to_1": 0.08
  "1_to_2": 0.10
  "2_to_3": 0.12
  "3_to_4": 0.15