global_defaults:
  age_mean: 35
  age_std_dev: 8
  min_working_age: 18
  max_working_age: 65
  comp_log_mean_factor: 1.0
  comp_spread_sigma: 0.25
  comp_base_salary: 45000
  comp_increase_per_age_year: 200
  comp_increase_per_tenure_year: 400
  comp_min_salary: 30000
  # Add additional defaults as needed, e.g.:
  # DEFAULT_COMP_LOG_MEAN_FACTOR: 1.0
  # DEFAULT_AGE_MEAN: 35
