# config/hazard_defaults.yaml
# Default parameters for generating the hazard table template.
# These values are based on architect suggestions and common HR analytics patterns.
# They should be reviewed and calibrated against specific company data or more detailed benchmarks.

global:
  simulation_years: [2024, 2025, 2026]
  job_levels: [1, 2, 3, 4, 5]         # Numeric job levels
  tenure_bands: ["<1", "1-3", "3-5", "5-10", "10-15", "15+"]
  cfg_scenario_name: "baseline"      # Default scenario name for the 'cfg' column

cola:
  # Year-specific Cost of Living Adjustments
  by_year: 
    2024: 0.025
    2025: 0.020
    2026: 0.018

termination:
  # Base termination rate for new hires (<1 year tenure)
  base_rate_for_new_hire: 0.25 
  
  # Multipliers for other tenure bands, applied to 'base_rate_for_new_hire'.
  # e.g., for "1-3", actual term_rate before level adjustment = 0.25 * 0.6 = 0.15
  tenure_multipliers: 
    "<1": 1.0    # New hire rate directly applies
    "1-3": 0.6   # Results in 15% (0.25 * 0.6)
    "3-5": 0.4   # Results in 10%
    "5-10": 0.28  # Results in 7%
    "10-15": 0.20 # Results in 5%
    "15+": 0.24  # Results in 6% (slight uptick for retirement/reshuffle)

  # Factor for discounting termination rate based on employee level.
  # Adjusted rate = current_rate * MAX(min_level_discount_multiplier, 1 - level_discount_factor * (level - 1))
  level_discount_factor: 0.10   # 10% reduction effect per level above L1
  min_level_discount_multiplier: 0.4 # Ensures the multiplier doesn't go below 0.4 (rate doesn't become too low)

promotion:
  # Base promotion probability before tenure and level adjustments.
  base_rate: 0.10 
  
  # Multipliers based on tenure band, applied to 'base_rate'.
  tenure_multipliers: 
    "<1": 0.5    # Lower chance in first year
    "1-3": 1.5   # Increased chance
    "3-5": 2.0   # Peak promotion window
    "5-10": 1.0   # Back to base influence
    "10-15": 0.3 # Lower chance
    "15+": 0.1   # Very low chance

  # Factor for dampening promotion rate based on employee level.
  # Adjusted rate = current_rate * MAX(0, 1 - level_dampener_factor * (level - 1))
  level_dampener_factor: 0.15 # Higher levels are harder to get promoted from/to

raises:
  # Base annual merit increase percentage.
  merit_base: 0.03
  
  # Tenure bands eligible for an additional merit bump.
  merit_tenure_bump_bands: ["<1", "1-3", "3-5"]
  merit_tenure_bump_value: 0.005 # The additional percentage for eligible tenure bands.
  
  # Levels eligible for an additional merit bump (e.g., for junior staff).
  merit_low_level_cutoff: 2 # Levels <= this cutoff get the bump.
  merit_low_level_bump_value: 0.005 # The additional percentage for eligible low levels.
  
  # Standard percentage increase upon promotion, in addition to merit/COLA.
  promotion_raise: 0.12
