# configs/default.yaml

# Global default parameters applied to all scenarios
global_parameters:
  start_year: 2025
  log_level: DEBUG
  projection_years: 5
  random_seed: 42
  dev_mode: true

  annual_compensation_increase_rate: 0.05
  annual_termination_rate:           0.15
  new_hire_termination_rate:         0.25
  new_hire_rate:                     0.17
  use_expected_attrition:            false

  # timing parameters (days into year)
  days_into_year_for_cola:           182
  days_into_year_for_promotion:      182

  # new-hire demographics & census template
  new_hire_average_age:              30
  census_template_path:             "data/census_template.parquet"

  deterministic_termination:         false
  monthly_transition:                false
  maintain_headcount:                false

  # role_distribution and role_compensation_params removed as part of schema refactoring

  new_hire_compensation_params:
    comp_base_salary:            55000
    comp_std:                    10000
    comp_increase_per_age_year:    500
    comp_increase_per_tenure_year: 1000
    comp_log_mean_factor:          1.0
    comp_spread_sigma:             0.3
    comp_min_salary:             40000

  onboarding:
    enabled: true
    early_tenure_months: 6
    hazard_multiplier:   1.5
    productivity_curve: [0.80, 0.85, 0.90, 0.95, 1.00, 1.00]

  plan_rules:
    eligibility:
      min_age: 21
      min_service_months: 0

    onboarding_bump:
      enabled: true
      method: sample_plus_rate
      rate: 0.05

    auto_enrollment:
      enabled: false
      window_days: 90
      proactive_enrollment_probability: 0.0
      proactive_rate_range: [0.0, 0.0]
      default_rate: 0.0
      re_enroll_existing: false
      opt_down_target_rate: 0.0
      increase_to_match_rate: 0.0
      increase_high_rate: 0.0
      outcome_distribution:
        prob_opt_out: 0.0
        prob_stay_default: 1.0
        prob_opt_down: 0.0
        prob_increase_to_match: 0.0
        prob_increase_high: 0.0

    auto_increase:
      enabled: false
      increase_rate: 0.0
      cap_rate: 0.0

    employer_match:
      tiers:
        - match_rate: 0.0
          cap_deferral_pct: 0.0
      dollar_cap: 0.0

    employer_nec:
      rate: 0.01

    irs_limits:
      2024:
        compensation_limit: 345000
        deferral_limit:       23000
        catchup_limit:        7500
        catchup_eligibility_age: 50
      2025:
        compensation_limit: 350000
        deferral_limit: 23500
        catchup_limit: 7500
        catchup_eligibility_age: 50
      2026:
        compensation_limit: 355000
        deferral_limit: 24000
        catchup_limit: 7500
        catchup_eligibility_age: 50
      2027:
        compensation_limit: 360000
        deferral_limit: 24500
        catchup_limit: 7500
        catchup_eligibility_age: 50
      2028:
        compensation_limit: 365000
        deferral_limit: 25000
        catchup_limit: 7500
        catchup_eligibility_age: 50
      2029:
        compensation_limit: 370000
        deferral_limit: 25500
        catchup_limit: 7500
        catchup_eligibility_age: 50

    behavioral_params:
      voluntary_enrollment_rate:    0.20
      voluntary_default_deferral:   0.05
      voluntary_window_days:        180
      voluntary_change_probability: 0.10
      prob_increase_given_change:   0.40
      prob_decrease_given_change:   0.30
      prob_stop_given_change:       0.05
      voluntary_increase_amount:    0.01
      voluntary_decrease_amount:    0.01

    contributions:
      enabled: true

    eligibility_events:
      milestone_months: []
      milestone_years:  []
      event_type_map:  {}

# Scenario definitions
scenarios:
  baseline:
    name: TinyDev