# Global default parameters applied to all scenarios
global_parameters:
  start_year: 2025
  projection_years: 5
  # Plan Rules
  eligibility:
    min_age: 21
    min_service_months: 0
  auto_enrollment:
    enabled: true
    proactive_enrollment_probability: 0.05
    proactive_rate_range: [0.01, 0.05]
    default_rate: 0.02
    re_enroll_existing: true
    outcome_distribution:
      prob_opt_out: 0.10
      prob_stay_default: 0.60
      prob_opt_down: 0.05
      prob_increase_to_match: 0.10
      prob_increase_high: 0.15
    opt_down_target_rate: 0.03
    increase_high_target_rate: 0.10
    window_days: 30
  auto_increase:
    enabled: true
    increase_rate: 0.01
    cap_rate: 0.10
  employer_match_formula: "1.0_of_1.0_up_to_6.0_pct"
  employer_nec_formula: "3.0_pct"
  irs_limits:
    2024:
      compensation_limit: 345000
      deferral_limit: 23000
      catchup_limit: 7500
      catchup_eligibility_age: 50
    2025:
      compensation_limit: 355000
      deferral_limit: 24000
      catchup_limit: 7500
      catchup_eligibility_age: 50
    2026:
      compensation_limit: 365000
      deferral_limit: 25000
      catchup_limit: 7500
      catchup_eligibility_age: 50
    2027:
      compensation_limit: 375000
      deferral_limit: 27000
      catchup_limit: 8000
      catchup_eligibility_age: 50
    2028:
      compensation_limit: 385000
      deferral_limit: 28000
      catchup_limit: 8000
      catchup_eligibility_age: 50
  behavioral_params:
    voluntary_enrollment_rate: 0.20
    voluntary_default_deferral: 0.05
    voluntary_window_days: 180
    voluntary_change_probability: 0.10
    prob_increase_given_change: 0.40
    prob_decrease_given_change: 0.30
    prob_stop_given_change: 0.05
    voluntary_increase_amount: 0.01
    voluntary_decrease_amount: 0.01
  annual_compensation_increase_rate: 0.03
  annual_termination_rate: 0.13
  new_hire_termination_rate: 0.20
  use_expected_attrition: false
  new_hire_start_salary: 55000
  new_hire_average_age: 30
  annual_growth_rate: 0.02
  monthly_transition: false
  hazard_model_params:
    file: data/hazard_model_params.yaml
  onboarding:
    enabled: true
    early_tenure_months: 6
    hazard_multiplier: 1.5
    productivity_curve: [0.80, 0.85, 0.90, 0.95, 1.00, 1.00]

# Scenario definitions with inheritance via anchors
scenarios:
  baseline: &baseline
    name: Baseline
    # inherits everything from global_parameters

  Baseline_ABM: 
    <<: *baseline
    name: Baseline_ABM

  proposed_ae_ai:
    <<: *baseline
    name: Proposed_AE_AI
    auto_enrollment:
      default_rate: 0.03
    auto_increase:
      cap_rate: 0.125
