name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi
        
    - name: Run quick tests
      run: |
        pytest -v -m quick
        
    - name: Run FutureWarning checks
      run: |
        # Check for FutureWarnings in run_one_year.py
        python -c "import warnings; warnings.filterwarnings('error', category=FutureWarning); import cost_model.engines.run_one_year" || echo "FutureWarnings detected! Please fix them."
